[project]
name = "CPyS"
version = "0.6.0"
authors = [
  { name="Stella Bourdin", email="stella.bourdin@lsce.ipsl.fr" },
]
description = "A python package from compute the Hart Cyclone Phase Space parameters"
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "pandas",
    "xarray",
    "pyproj",
    "matplotlib",
    "scipy",
]

[tool.setuptools]
packages = ["CPyS"]
