[project]
name = "cpys"
version = "1.0.0"
authors = [
  { name="Stella Bourdin", email="stella.bourdin@lsce.ipsl.fr" },
]
description = "A python package from compute the Hart Cyclone Phase Space parameters"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "xarray",
    "matplotlib",
    "scipy>=1.16.0",
    "huracanpy",
]

[tool.setuptools]
packages = ["cpys"]

[tool.ruff]
include = ["cpys/**/*.py"]

[tool.ruff.lint]
extend-select = [
    "N", # pep8 naming conventions
]

[tool.pytest]
testpaths = ["tests"]
